### ISSUE TITLE
invisible cursor in vim

### ISSUE THREAD

**Issue by AwesomePatrol** [jan-warchol/selenized#35]
I am using dark urxvt theme and selenized color scheme in vim.

Following pictures were taken on vanilla themes except the background color of line number column.

![right_parent](https://cloud.githubusercontent.com/assets/8083990/25421790/aeb14f2a-2a5e-11e7-9e6c-141e88a80301.png)
Cursor on the right parentheses of `main`.

![right_bracket](https://cloud.githubusercontent.com/assets/8083990/25421793/aeb2e4c0-2a5e-11e7-9cc0-8a25fcabb932.png)

Cursor on the closing curly bracket of the `main`.

![right_bracket_unfocused](https://cloud.githubusercontent.com/assets/8083990/25421791/aeb17806-2a5e-11e7-94e1-4fd5793f7491.png)
Same as before, but window is not focused.

![normal_focused](https://cloud.githubusercontent.com/assets/8083990/25421789/aeb1291e-2a5e-11e7-83f4-fc6670433daa.png)
For comparison, cursor on the focused window.

![normal_unfocused](https://cloud.githubusercontent.com/assets/8083990/25421792/aeb2c4d6-2a5e-11e7-91fc-1b9a6f9049ee.png)
Unfocused window.

I noticed that character below is turning white, but it is really hard to notice.

**Comment by jan-warchol** [comment]
Thanks for the report! I'll debug this when I'll have some spare time during May holidays :)

**Comment by dngray** [comment]
This bug is fixed I believe. This is using the ColorTemplate version with Alacritty that has just been merged:

![right_parentheses_main](https://user-images.githubusercontent.com/48640805/76144161-98401c80-6075-11ea-95f2-e4683ae2b2a3.png)
Cursor on the right parentheses of `main`.

![right_curly](https://user-images.githubusercontent.com/48640805/76144168-a7bf6580-6075-11ea-8734-ef31c2a1eaf0.png)
Cursor on the closing curly bracket of the `main`.

![right_curly_unfocused](https://user-images.githubusercontent.com/48640805/76144177-be65bc80-6075-11ea-8751-1048d1c5f9aa.png)
Same as before, but window is not focused.

![focused](https://user-images.githubusercontent.com/48640805/76144193-d0475f80-6075-11ea-8745-293cbc071ef8.png)
For comparison, cursor on the focused window.

![unfocused](https://user-images.githubusercontent.com/48640805/76144199-d9383100-6075-11ea-859a-6e88e8c93451.png)
Unfocused window.

**Comment by jan-warchol** [comment]
Indeed, I remember changing highlight rules for matching parenthesis at some point. @AwesomePatrol I'm closing the issue, but feel free to reopen if latest master doesn't work for you.
